name: Release

on:
  push:
    branches:
      - production

jobs:
  Deploy-Staging:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-staging
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        name: deploy
        run: |
          echo "deploy stuff"
  Deploy-Production:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-production
    environment: production
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        name: deploy
        run: |
          echo "deploy stuff"
