name: Release

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        name: deploy
        run: |
          echo "deploy stuff"