name: Release

on:
  push:
    branches:
      - main

jobs:
  Deploy-Staging:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        name: deploy
        run: |
          echo "deploy stuff"
  Deploy-Production:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    environment: production
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        name: deploy
        run: |
          echo "deploy stuff"
