name: Tests

on:
  push:
  pull_request:

permissions:
  statuses: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: test
        name: test
        run: |
          echo ${{ github.event.before }}
      - name: Create Atlantis Commit Status
        uses: actions/github-script@v6
        with:
          hello: ${{ github.ref == 'main' }}
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.payload.repository.name,
              repo: context.payload.repository.owner.login,
              sha: context.payload.merge_group.head_sha,
              state: 'success',
              description: 'dummy commit status for merge group',
              context: 'merge_group'
            });
