name: Tests

on:
  push:

jobs:
  test:
    if: ${{ fromJson(vars.HELLO)[github.ref] != null }}
    runs-on: ubuntu-latest
    steps:
      - id: test
        name: test
        run: |
          echo ${{ github.event.before }}
