name: Tests

on:
  push:
env:
  test: ${{ fromJson(secrets.HELLO)[github.ref] }}'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: test
        if: env.test && fromJson(env.secrets.HELLO)["hell"]
        name: test
        run: |
          echo ${{ github.event.before }}
