name: Tests

on:
  push:
env:
  test: ${{ fromJson(secrets.HELLO)[github.ref] }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: test
        if: fromJson(env.secrets.HELLO)[github.ref]
        name: test
        run: |
          echo ${{ github.event.before }}
