name: Tests

on:
  push:
env:
  map: |
    {"hello": "world"}
  test: ${{ fromJson(secrets.HELLO)["hell"] }}'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: test
        if: env.test && fromJson(env.map)["hell"]
        name: test
        env:
          test: fromJson(env.map)["hello"]
        run: |
          echo ${{ github.event.before }}
