name: Tests

on:
  push:
env:
  map: |
    {"hello": "world"}
  test: ${{ fromJson(env.map)["hello"] }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: test
        if: env.test && null
        name: test
        run: |
          echo ${{ github.event.before }}
