name: Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: test
        if: fromJson(vars.HELLO)[github.ref]
        name: test
        run: |
          echo ${{ github.event.before }}
