name: Tests

on:
  push:

permissions:
  statuses: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: test
        name: test
        run: |
          echo ${{ github.event.before }}
      - name: Create Atlantis Commit Status
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.G_TOKEN }}
          script: |
            const updateStatus = (statusName) => github.rest.repos.createCommitStatus({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              sha: context.sha,
              state: 'success',
              description: 'dummy commit status for merge group',
              context: statusName
            });
            await Promise.all([
              updateStatus('atlantis/apply'),
              updateStatus('atlantis/plan'),
            ]);
