name: Tests

on:
  push:
  pull_request:
    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: test
        name: test
        run: |
          echo ${{ github.event.before }}
      - name: Create Atlantis Commit Status
        uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context))
