name: Tests

on:
  push:
    branches-ignore:
      - main
      - production

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: test
        name: test
        run: |
          echo "test stuff"